import asyncio
import io
import json
import logging
import uuid
import zipfile
from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from sse_starlette.sse import EventSourceResponse
from app.models import (
    GenerateRequest,
    GenerateResponse,
    DownloadRequest,
    RepromptRequest,
    RepromptResponse,
)
from app.services.pipeline import run_pipeline
from app.services.llm.factory import get_llm_provider
from app.services.generator import slugify, convert_base_to_md

logger = logging.getLogger("app.router.generate")

router = APIRouter()

jobs: dict[str, dict] = {}


@router.post("/generate", response_model=GenerateResponse)
async def create_job(req: GenerateRequest):
    job_id = str(uuid.uuid4())
    event_queue = asyncio.Queue()

    jobs[job_id] = {
        "status": "pending",
        "url": str(req.url),
        "client_info": req.client_info,
        "pages_found": 0,
        "markdown": None,
        "markdown_md": None,
        "llms_ctx": None,
        "child_pages": [],
        "error": None,
        "event_queue": event_queue,
    }

    logger.info("Job %s created for URL: %s (client_info: %s)", job_id, req.url, "yes" if req.client_info else "no")

    asyncio.create_task(run_pipeline(job_id, str(req.url), jobs))

    return GenerateResponse(job_id=job_id)


@router.get("/generate/{job_id}/stream")
async def stream_job(job_id: str):
    """SSE endpoint. Client connects here after POST /generate returns job_id."""
    if job_id not in jobs:
        logger.warning("SSE stream requested for unknown job: %s", job_id)
        return {"error": "Job not found"}

    job = jobs[job_id]
    logger.info("SSE stream opened for job %s (current status: %s)", job_id, job["status"])

    async def event_generator():
        queue: asyncio.Queue = job["event_queue"]

        while True:
            event = await queue.get()
            event_type = event["type"]
            logger.debug("SSE yielding event '%s' for job %s", event_type, job_id)

            if event_type == "progress":
                yield {
                    "event": "progress",
                    "data": json.dumps({
                        "status": event.get("status", "processing"),
                        "pages_found": event.get("pages_found", 0),
                        "message": event.get("message", ""),
                        "step": event.get("step"),
                        "step_state": event.get("step_state"),
                        "summary": event.get("summary"),
                        "detail": event.get("detail"),
                    }),
                }

            elif event_type == "complete":
                md_len = len(event.get("markdown", ""))
                logger.info("SSE complete for job %s (%d chars of markdown)", job_id, md_len)
                yield {
                    "event": "complete",
                    "data": json.dumps({
                        "markdown": event["markdown"],
                        "job_id": job_id,
                    }),
                }
                return

            elif event_type == "error":
                logger.error("SSE error for job %s: %s", job_id, event["message"])
                yield {
                    "event": "error",
                    "data": json.dumps({
                        "message": event["message"],
                    }),
                }
                return

    return EventSourceResponse(event_generator(), ping=15)


@router.post("/generate/{job_id}/download.zip")
async def download_zip(job_id: str, req: DownloadRequest):
    """Download full archive using the user's current edited markdown.

    Generates base/llms.txt from the provided markdown, md/llms.txt by
    replacing URLs with .md links only where a .md file was actually generated,
    plus llms-ctx.txt and the individual .md files from the pipeline.
    """
    if job_id not in jobs:
        return {"error": "Job not found"}

    job = jobs[job_id]
    if job["status"] != "completed":
        return {"error": "Job not completed"}

    child_pages = job.get("child_pages", [])
    site_url = job.get("url", "")

    # Use the user's current edited markdown for base
    base_markdown = req.markdown

    # Build md version from the edited markdown — only replaces URLs
    # that have a corresponding .md file generated by the pipeline
    md_markdown = convert_base_to_md(base_markdown, child_pages, site_url) if child_pages else base_markdown

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, 'w', zipfile.ZIP_DEFLATED) as zf:
        # Base llms.txt (original URLs)
        zf.writestr("base/llms.txt", base_markdown)

        # MD llms.txt (.md file URLs where available, original URLs otherwise)
        zf.writestr("md/llms.txt", md_markdown)

        # llms-ctx.txt (expanded context from pipeline)
        if job.get("llms_ctx"):
            zf.writestr("llms-ctx.txt", job["llms_ctx"])

        # Individual .md files
        seen_names: set[str] = set()
        for cp in child_pages:
            name = slugify(cp.title if hasattr(cp, 'title') else cp['title'])
            base_name = name
            counter = 1
            while name in seen_names:
                name = f"{base_name}-{counter}"
                counter += 1
            seen_names.add(name)

            content = cp.markdown_content if hasattr(cp, 'markdown_content') else cp['markdown_content']
            zf.writestr(f"md/{name}.md", content)

    buf.seek(0)
    return StreamingResponse(
        buf,
        media_type="application/zip",
        headers={"Content-Disposition": "attachment; filename=llms-txt.zip"},
    )


@router.post("/reprompt", response_model=RepromptResponse)
async def reprompt(req: RepromptRequest):
    """Synchronous LLM call to modify existing markdown based on user instruction."""
    from app.config import settings

    logger.info("Reprompt for job %s: %s", req.job_id, req.instruction[:100])

    if settings.mock_llm:
        logger.debug("Using mock reprompt (MOCK_LLM=true)")
        return RepromptResponse(
            markdown=req.current_markdown + f"\n\n<!-- Mock reprompt: {req.instruction} -->\n"
        )

    llm = get_llm_provider()
    updated_markdown = await llm.reprompt(req.current_markdown, req.instruction)
    logger.info("Reprompt complete for job %s (%d chars)", req.job_id, len(updated_markdown))
    return RepromptResponse(markdown=updated_markdown)
